export function buildPlaywrightConfig(opts: {
  baseUrl: string;
  browserName: string;
  headless: boolean;
  testDir?: string;
  testMatch?: string;
  outputDir?: string;
}): string {
  const testDir = opts.testDir ?? "/work";
  const testMatch = opts.testMatch ?? "player.spec.ts";
  const outputDir = opts.outputDir ?? "/work/test-results";

  return `// Auto-generated by PlaywrightQuest — do not edit
module.exports = {
  testDir: '${testDir}',
  testMatch: ['${testMatch}'],
  timeout: 20000,
  expect: { timeout: 5000 },
  workers: 1,
  retries: 0,
  reporter: [['line']],
  use: {
    baseURL: '${opts.baseUrl}',
    headless: ${opts.headless},
    screenshot: 'only-on-failure',
    trace: 'on',
    video: 'on',
  },
  projects: [{ name: '${opts.browserName}', use: { browserName: '${opts.browserName}' } }],
  outputDir: '${outputDir}',
};
`;
}
