export function buildPlaywrightConfig(opts: {
  baseUrl: string;
  browserName: string;
  headless: boolean;
  testDir?: string;
  testMatch?: string;
  outputDir?: string;
}): string {
  const testDir = opts.testDir ?? "/work";
  const testMatch = opts.testMatch ?? "player.spec.ts";
  const outputDir = opts.outputDir ?? "/work/test-results";

  // JSON.stringify produces double-quoted, fully-escaped JS string literals.
  // Critical on Windows: a raw template like `'${testDir}'` injects a path
  // such as C:\Users\foo\Temp into a JS source file where \U, \T, \t etc.
  // are escape sequences, mangling the path when Node parses the config.
  const q = (s: string) => JSON.stringify(s);

  return `// Auto-generated by PlaywrightQuest — do not edit
module.exports = {
  testDir: ${q(testDir)},
  testMatch: [${q(testMatch)}],
  timeout: 20000,
  expect: { timeout: 5000 },
  workers: 1,
  retries: 0,
  reporter: [['line']],
  use: {
    baseURL: ${q(opts.baseUrl)},
    headless: ${opts.headless},
    screenshot: 'only-on-failure',
    trace: 'on',
    video: 'on',
  },
  projects: [{ name: ${q(opts.browserName)}, use: { browserName: ${q(opts.browserName)} } }],
  outputDir: ${q(outputDir)},
};
`;
}
